# Generated by Django 2.1.3 on 2018-11-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePredio', models.CharField(max_length=200)),
                ('andar', models.CharField(max_length=20)),
                ('ladoAndar', models.CharField(max_length=80)),
                ('nomeSala', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'sala',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('celular', models.IntegerField()),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
