# Generated by Django 2.1.3 on 2018-11-06 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myreservasapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='flagPontoRede',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sala',
            name='flagRecursosVisuais',
            field=models.BooleanField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sala',
            name='qtdPessoasSentadas',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sala',
            name='qtdlotacaoMax',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sala',
            name='nomePredio',
            field=models.CharField(max_length=100),
        ),
    ]
