# Generated by Django 2.1.3 on 2018-11-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreservasapp', '0002_auto_20181106_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePredio', models.CharField(max_length=100)),
                ('andar', models.CharField(max_length=20)),
                ('ladoAndar', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'localidade',
            },
        ),
        migrations.RemoveField(
            model_name='sala',
            name='andar',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='ladoAndar',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='nomePredio',
        ),
    ]
