# Generated by Django 2.1.3 on 2018-11-06 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myreservasapp', '0003_auto_20181106_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='idlocalidade',
            field=models.ForeignKey(blank=True, db_column='idLocalidade', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myreservasapp.Localidade'),
        ),
    ]
