# Generated by Django 2.1.3 on 2018-11-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myreservasapp', '0004_sala_idlocalidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='idlocalidade',
        ),
    ]
