# Generated by Django 2.1.3 on 2018-11-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreservasapp', '0005_remove_sala_idlocalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahorareserva', models.DateTimeField(blank=True, db_column='dataHoraReserva', null=True, unique=True)),
                ('tituloreserva', models.CharField(blank=True, db_column='tituloReserva', max_length=60, null=True)),
            ],
            options={
                'db_table': 'reserva',
                'managed': True,
            },
        ),
    ]
