# Generated by Django 2.1.3 on 2018-11-06 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myreservasapp', '0006_reserva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
    ]
