# Generated by Django 2.1.3 on 2018-11-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreservasapp', '0007_auto_20181106_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='flagPontoRede',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='sala',
            name='flagRecursosVisuais',
            field=models.CharField(max_length=1),
        ),
    ]
