# Generated by Django 2.1.3 on 2018-11-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myreservasapp', '0008_auto_20181106_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='datahorareserva',
        ),
    ]
