# Generated by Django 2.1.3 on 2018-11-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreservasapp', '0009_remove_reserva_datahorareserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='datahorareserva',
            field=models.DateTimeField(blank=True, db_column='dataHoraReserva', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='flagPontoRede',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sala',
            name='flagRecursosVisuais',
            field=models.BooleanField(),
        ),
    ]
