# Generated by Django 2.1.3 on 2018-11-07 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myreservasapp', '0010_auto_20181106_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='idSala',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='idUsuario',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sala',
            name='idlocalidade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
