# Generated by Django 2.1.3 on 2018-11-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreservasapp', '0012_auto_20181109_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='idlocalidade',
            field=models.IntegerField(db_column='idlocalidade'),
        ),
    ]
